---
# Zadania instalujące Tmux.
# Używamy ansible_facts, ponieważ ansible_os_family jest deprecated.

- import_tasks: debian.yaml
  when: ansible_facts['os_family'] == "Debian"

- import_tasks: darwin.yaml
  when: ansible_facts['os_family'] == "Darwin"
