---

- block:

  - name: "▶️ [fonts:darwin] Start: installing macOS fonts via Homebrew Cask"
    ansible.builtin.debug:
      msg: "Instaluję fonty dla macOS: font-powerline-symbols, meslo nerd font, fira code nerd font, symbols nerd font, jetbrains mono nerd font..."

  - name: "install fonts"
    community.general.homebrew_cask:
      name:
        - font-powerline-symbols
        - font-meslo-lg-nerd-font
        - font-fira-code-nerd-font
        - font-symbols-only-nerd-font
        # - font-jetbrains-mono
        - font-jetbrains-mono-nerd-font
      install_options: no-quarantine
      accept_external_apps: true

  tags:
    - font_install
    - homebrew
