---

- name: "▶️ [fonts:debian] Start: installing FiraCode font"
  ansible.builtin.debug:
    msg: "Instaluję font: fonts-firacode"

- name: "install firacode font"
  become: true
  ansible.builtin.apt:
    name: fonts-firacode
    update_cache: true
    autoclean: true
    autoremove: true

- name: "▶️ [fonts:debian] Start: installing Powerline font"
  ansible.builtin.debug:
    msg: "Instaluję font: fonts-powerline"

- name: "install powerline font"
  become: true
  ansible.builtin.apt:
    name: fonts-powerline
    update_cache: true
    autoclean: true
    autoremove: true
