---
# Zadania instalujące fonty.
# Używamy ansible_facts, ponieważ ansible_os_family jest deprecated.

- import_tasks: darwin.yaml
  when: ansible_facts['os_family'] == "Darwin"

- import_tasks: debian.yaml
  when: ansible_facts['os_family'] == "Debian"
